spring.application.name=yokubaro
# H2データベースの有効化と接続設定
spring.datasource.url=jdbc:h2:mem:yokubarodb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console（ブラウザで中身を見る管理画面）を有効にする
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SQL自動実行を有効にする設定（重要）
spring.sql.init.mode=always